config/routes.rb
Rails.application.routes.draw do
  root 'quotes#index'
  resources :quotes do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :quota

  validates :text, presence: true
end

app/models/evaluate.rb
class Evaluate < ApplicationRecord
  belongs_to :quota
  belongs_to :evaluatable, polymorphic: true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/quota.rb
class Quota < ApplicationRecord
  has_many :quotes
  has_many :skins, through: :skin_quotas
  has_many :pictures, as: :imageable
  has_many :evaluates, as: :evaluatable

end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :quota, optional: true
  has_many :pictures, as: :imageable
  has_many :evaluates, as: :evaluatable
  has_many :comments, as: :commentable, dependent: :destroy

  validates :text, presence: true
end

app/models/skin.rb
class Skin < ApplicationRecord
  has_many :quotas, through: :skin_quotas
end

app/models/skin_quota.rb
class SkinQuota < ApplicationRecord
  belongs_to :skin
  belongs_to :quota, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @quote = Quote.find(params[:quote_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(quota_id: 1, commentable: @quote)
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :random_quote

  def index
    redirect_to quote_path(random_quote)
  end

  def show
    @quote = Quote.find(params[:id])
    other_quotes = Quote.where.not(id: @quote.id).includes(:quota, :comments)
    @uQuotes = other_quotes.where(quota_id: @quote.quota_id)
    @aQuotes = other_quotes.where(author: @quote.author)
    @sQuotes = other_quotes.where(source: @quote.source)

    @comment = Comment.new
    @comments = @quote.comments
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(quote_params)
    if @quote.save
      redirect_to quote_path(@quote.id)
    else
      render :new
    end
  end

  def edit
    @quote = Quote.find(params[:id])
  end

  def update
    @quote = Quote.find(params[:id])
    if @quote.update(quote_params)
      redirect_to quote_path(params[:id])
    else
      render :edit
    end
  end

  private

  def quote_params
    proto = {}
    merges = {quota_id: 1, selfquote: 1}
    if params[:quote][:source].present? || params[:quote][:author].present?
      merges.merge!({selfquote: 0})
    end
    proto = params.require(:quote).permit(:text, :author, :source, :description).merge(merges)
    return proto
  end

  def random_quote
    rand(1..Quote.count)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/comments/index.html.haml
.comments
  %h3 Comments
  - @comments.each do |comment|
    = comment.text

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quota2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0" user-scalable=no>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/_form.html.haml
.form
  .title
    Post a Quote
  = form_with model: @quote, class: 'form__quote', local: true do |f|
    = f.text_area :text, placeholder: 'quote here', class: 'text_box'
    .form__quote__origin
      = f.text_field :author, placeholder: 'person source', class: 'text_box', id: 'author'
      = f.text_field :source, placeholder: 'document source', class: 'text_box'
      = f.text_field :date, placeholder: 'source date', class: 'text_box', id: 'source'
    = f.text_area :description, placeholder: 'additional history to mension', class: 'text_box'
    .form__quote__similar
      similar quotes
    = f.submit 'Quote!', class: 'submit'

app/views/quotes/_main.html.haml
%header
  .title
    .title__logo
      %span.q Q
      %span.u u
      %span.o o
      %span.t t
      %span.a a
    .title__sub
      \-for people who wants quotes-
  .user_menu
    .user_menu__login
      login
    .user_menu__setting
      user
= render partial: 'quota'
= render partial: 'menu'
.main
  .main__text
    = render partial: 'quote'

    

.mask.hidden

app/views/quotes/_menu.html.haml
%ul.menu
  %li.similar_quote
    find similar quotes
  %li.other_quote
    = link_to "reload quote", root_path
  %li.new_quote
    = link_to "new quote", new_quote_path
  %li.edit_quote
    = link_to "edit quote", edit_quote_path(@quote.id)
  %li.user
    find friends

app/views/quotes/_quota.html.haml
.quota
  Q
  .devider
    .plus

app/views/quotes/_quote.html.haml
.quote.top.0
  .quote__header.0
    .quote__header__btns
      %button.qButton.0{type: 'button'} Q
      %button.gButton.0{type: 'button'} G
      %button.cButton.0{type: 'button'} C
    .popup.0
  .quote__content.top
    .quote__content__left
      -# - if @quote.author && @quote.author.pictures.present?
      -#   = image_tag @quote.author.pictures.sample, size: "100x100"
      -# - elsif @quote.source && @quote.source.pictures.present?
      -#   = image_tag @quote.source.pictures.sample, size: "100x100"
    .quote__content__text.0
      = @quote.text
      .quote__content__text__jp
    .quote__content__origin.0
      -# .origin__name
      -#   -if @author
      -#     \-
      -#     = link_to @author.name, '#aName' ,class: 'aName'
      -#     - if @source
      -#       \,
      -#   -elsif @quote.selfquote
      -#     = link_to @quote.quota.name, '#qName' , class: 'qName'
      -# - if @source
      -#   .origin__source
      -#     = link_to @source.name, '#sName', class: 'sName'
  .quote__footer
    .quote__footer__like
      %button.like
        L
      .quote__footer__like__times
        0
  .comments.0
    .comments__header
      %h3 Comments
      %button.close{type: 'button'} X
    - @comments.each do |comment|
      .comments__each
        = comment.text
        .comments__each__quota
          posted by
          %span #{comment.quota.name},
          at #{comment.updated_at}
    = form_with model: [@quote, @comment], class: 'comment_form', local: true do |f|
      %button.nButton.0{type: 'button'} N
      = f.text_field :text, class: 'comment__text'
      = f.submit '', class: 'submit'

app/views/quotes/edit.html.haml
= render partial: 'form'

app/views/quotes/index.html.haml
%header
  .title
    .title__logo
      %span.q Q
      %span.u u
      %span.o o
      %span.t t
      %span.a a
    .title__sub
      \-for people who wants quotes-
  .user_menu
    .user_menu__login
      login
    .user_menu__setting
      user
= render partial: 'quota'
= render partial: 'menu'
.main
  .main__text
    = render partial: 'quote'

.mask.hidden

app/views/quotes/new.html.haml
.new
  .title
    Post a Quote
  = form_with model: @quote, class: 'new__quote', local: true do |f|
    = f.text_area :text, placeholder: 'quote here', class: 'text_box'
    .new__quote__origin
      = f.fields_for :author do |a|
        = a.text_field :name, placeholder: 'says whom?', class: 'text_box'
      = f.fields_for :document do |d|
        = d.text_field :name, placeholder: 'document or article', class: 'text_box'
    = f.text_area :description, placeholder: 'additional history to mension', class: 'text_box'
    .new__quote__img
      = f.fields_for :picture do |p|
        = f.label :image, 'image file'
        = f.file_field :image, class: 'file_form'
    .new__quote__similar
      similar quotes
    .new__quote__tags
      tags
    = f.submit 'Quote!', class: 'submit'

app/views/quotes/show.html.haml
= render partial: 'main'